# Part 1: ETL
## World Happiness Report 2016 - 2020

In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine

# EXTRACT
Store datasets into DataFrames

### Dataset 1: 2020
 - Webscrape from Wikipedia
 - Store webscraped data into DataFrame

In [2]:
# 2020 table:
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report#2020_report'

In [3]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2020 World Happiness Report, released on M...,
                                         Descriptions
 0  The 2019 World Happiness Report focuses commun...,
                                         Descriptions
 0  The 2018 iteration was released on 20 March an...,
                                         Descriptions
 0  The fifth World Happiness Report emphasizes th...,
                                         Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 150                                                149
 151                                                150
 152                                                151
 153                                                152
 154                                                153

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.809           1.285           1.500
 3                     Denmark      7.646           1.327           1.503
 4                 Switzerland      7.560           1.391           1.472
 ..                        ...        ...             ...             ...
 150  Central African Republic      3.476           0.041           0.000
 151                    Rwanda      3.312           0.343           0.523
 152                  Zimbabwe      3.299           0.426           1.048
 153               South Sudan      2.817           0.289           0.553
 154               Afghanistan      2.567           0.301           0.356

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.961                         0.662       0.160
 3                      0.979                         0.665       0.243
 4                      1.041                         0.629       0.269
 ..                       ...                           ...         ...
 150                    0.000                         0.293       0.254
 151                    0.572                         0.604       0.236
 152                    0.375                         0.377       0.151
 153                    0.209                         0.066       0.210
 154                    0.266                         0.000       0.135

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.478
 3                        0.495
 4                        0.408
 ..                         ...
 150                      0.028
 151                      0.486
 152                      0.081
 153                      0.111
 154                      0.001

 [155 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.809           1.285
 1               2                   Denmark  7.646           1.327
 2               3               Switzerland  7.560           1.391
 3               4                   Iceland  7.504           1.327
 4               5                    Norway  7.488           1.424
 ..            ...                       ...    ...             ...
 148           149  Central African Republic  3.476           0.041
 149           150                    Rwanda  3.312           0.343
 150           151                  Zimbabwe  3.299           0.426
 151           152               South Sudan  2.817           0.289
 152           153               Afghanistan  2.567           0.301

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.500                    0.961                         0.662
 1             1.503                    0.979                         0.665
 2             1.472                    1.041                         0.629
 3             1.548                    1.001                         0.662
 4             1.495                    1.008                         0.670
 ..              ...                      ...                           ...
 148           0.000                    0.000                         0.293
 149           0.523                    0.572                         0.604
 150           1.048                    0.375                         0.377
 151           0.553                    0.209                         0.066
 152           0.356                    0.266                         0.000

      Generosity  Perceptions of corruption
 0         0.160                      0.478
 1         0.243                      0.495
 2         0.269                      0.408
 3         0.362                      0.145
 4         0.288                      0.434
 ..          ...                        ...
 148       0.254                      0.028
 149       0.236                      0.486
 150       0.151                      0.081
 151       0.210                      0.111
 152       0.135                      0.001

 [153 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.769           1.340           1.587
 3                     Denmark      7.600           1.383           1.573
 4                      Norway      7.554           1.488           1.582
 ..                        ...        ...             ...             ...
 153                    Rwanda      3.334           0.359           0.711
 154                  Tanzania      3.231           0.476           0.885
 155               Afghanistan      3.203           0.350           0.517
 156  Central African Republic      3.083           0.026           0.000
 157               South Sudan      2.853           0.306           0.575

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.986                         0.596       0.153
 3                      0.996                         0.592       0.252
 4                      1.028                         0.603       0.271
 ..                       ...                           ...         ...
 153                    0.614                         0.555       0.217
 154                    0.499                         0.417       0.276
 155                    0.361                         0.000       0.158
 156                    0.105                         0.225       0.235
 157                    0.295                         0.010       0.202

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.410
 4                        0.341
 ..                         ...
 153                      0.411
 154                      0.147
 155                      0.025
 156                      0.035
 157                      0.091

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[48] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                    1               3
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                      Norway      7.537            0.039           1.616
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2             1.534                    0.797                         0.635
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2         0.362       0.316       2.277
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0              1              3                    Norway  7.537
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...

In [42]:
df2020_raw = tables[9]
df2020_raw.head(200)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.809,1.285,1.500,0.961,0.662,0.160,0.478
1,2,Denmark,7.646,1.327,1.503,0.979,0.665,0.243,0.495
2,3,Switzerland,7.560,1.391,1.472,1.041,0.629,0.269,0.408
3,4,Iceland,7.504,1.327,1.548,1.001,0.662,0.362,0.145
4,5,Norway,7.488,1.424,1.495,1.008,0.670,0.288,0.434
...,...,...,...,...,...,...,...,...,...
148,149,Central African Republic,3.476,0.041,0.000,0.000,0.293,0.254,0.028
149,150,Rwanda,3.312,0.343,0.523,0.572,0.604,0.236,0.486
150,151,Zimbabwe,3.299,0.426,1.048,0.375,0.377,0.151,0.081
151,152,South Sudan,2.817,0.289,0.553,0.209,0.066,0.210,0.111
152,153,Afghanistan,2.567,0.301,0.356,0.266,0.000,0.135,0.001

### Dataset 2: 2019
 - Webscrape from Wikipedia
 - Store webscraped data into DataFrame

In [23]:
# 2019 table:
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report#2019_report'

In [24]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2020 World Happiness Report, released on M...,
                                         Descriptions
 0  The 2019 World Happiness Report focuses commun...,
                                         Descriptions
 0  The 2018 iteration was released on 20 March an...,
                                         Descriptions
 0  The fifth World Happiness Report emphasizes th...,
                                         Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 150                                                149
 151                                                150
 152                                                151
 153                                                152
 154                                                153

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.809           1.285           1.500
 3                     Denmark      7.646           1.327           1.503
 4                 Switzerland      7.560           1.391           1.472
 ..                        ...        ...             ...             ...
 150  Central African Republic      3.476           0.041           0.000
 151                    Rwanda      3.312           0.343           0.523
 152                  Zimbabwe      3.299           0.426           1.048
 153               South Sudan      2.817           0.289           0.553
 154               Afghanistan      2.567           0.301           0.356

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.961                         0.662       0.160
 3                      0.979                         0.665       0.243
 4                      1.041                         0.629       0.269
 ..                       ...                           ...         ...
 150                    0.000                         0.293       0.254
 151                    0.572                         0.604       0.236
 152                    0.375                         0.377       0.151
 153                    0.209                         0.066       0.210
 154                    0.266                         0.000       0.135

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.478
 3                        0.495
 4                        0.408
 ..                         ...
 150                      0.028
 151                      0.486
 152                      0.081
 153                      0.111
 154                      0.001

 [155 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.809           1.285
 1               2                   Denmark  7.646           1.327
 2               3               Switzerland  7.560           1.391
 3               4                   Iceland  7.504           1.327
 4               5                    Norway  7.488           1.424
 ..            ...                       ...    ...             ...
 148           149  Central African Republic  3.476           0.041
 149           150                    Rwanda  3.312           0.343
 150           151                  Zimbabwe  3.299           0.426
 151           152               South Sudan  2.817           0.289
 152           153               Afghanistan  2.567           0.301

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.500                    0.961                         0.662
 1             1.503                    0.979                         0.665
 2             1.472                    1.041                         0.629
 3             1.548                    1.001                         0.662
 4             1.495                    1.008                         0.670
 ..              ...                      ...                           ...
 148           0.000                    0.000                         0.293
 149           0.523                    0.572                         0.604
 150           1.048                    0.375                         0.377
 151           0.553                    0.209                         0.066
 152           0.356                    0.266                         0.000

      Generosity  Perceptions of corruption
 0         0.160                      0.478
 1         0.243                      0.495
 2         0.269                      0.408
 3         0.362                      0.145
 4         0.288                      0.434
 ..          ...                        ...
 148       0.254                      0.028
 149       0.236                      0.486
 150       0.151                      0.081
 151       0.210                      0.111
 152       0.135                      0.001

 [153 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.769           1.340           1.587
 3                     Denmark      7.600           1.383           1.573
 4                      Norway      7.554           1.488           1.582
 ..                        ...        ...             ...             ...
 153                    Rwanda      3.334           0.359           0.711
 154                  Tanzania      3.231           0.476           0.885
 155               Afghanistan      3.203           0.350           0.517
 156  Central African Republic      3.083           0.026           0.000
 157               South Sudan      2.853           0.306           0.575

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.986                         0.596       0.153
 3                      0.996                         0.592       0.252
 4                      1.028                         0.603       0.271
 ..                       ...                           ...         ...
 153                    0.614                         0.555       0.217
 154                    0.499                         0.417       0.276
 155                    0.361                         0.000       0.158
 156                    0.105                         0.225       0.235
 157                    0.295                         0.010       0.202

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.410
 4                        0.341
 ..                         ...
 153                      0.411
 154                      0.147
 155                      0.025
 156                      0.035
 157                      0.091

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[48] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                    1               3
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                      Norway      7.537            0.039           1.616
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2             1.534                    0.797                         0.635
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2         0.362       0.316       2.277
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0              1              3                    Norway  7.537
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...

In [43]:
df2019_raw = tables[11]
df2019_raw.head(200)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

### Dataset 3: 2018
 - Webscrape from Wikipedia
 - Store webscraped data into DataFrame

In [28]:
# 2018 table:
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report#2018_report'

In [29]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2020 World Happiness Report, released on M...,
                                         Descriptions
 0  The 2019 World Happiness Report focuses commun...,
                                         Descriptions
 0  The 2018 iteration was released on 20 March an...,
                                         Descriptions
 0  The fifth World Happiness Report emphasizes th...,
                                         Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 150                                                149
 151                                                150
 152                                                151
 153                                                152
 154                                                153

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.809           1.285           1.500
 3                     Denmark      7.646           1.327           1.503
 4                 Switzerland      7.560           1.391           1.472
 ..                        ...        ...             ...             ...
 150  Central African Republic      3.476           0.041           0.000
 151                    Rwanda      3.312           0.343           0.523
 152                  Zimbabwe      3.299           0.426           1.048
 153               South Sudan      2.817           0.289           0.553
 154               Afghanistan      2.567           0.301           0.356

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.961                         0.662       0.160
 3                      0.979                         0.665       0.243
 4                      1.041                         0.629       0.269
 ..                       ...                           ...         ...
 150                    0.000                         0.293       0.254
 151                    0.572                         0.604       0.236
 152                    0.375                         0.377       0.151
 153                    0.209                         0.066       0.210
 154                    0.266                         0.000       0.135

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.478
 3                        0.495
 4                        0.408
 ..                         ...
 150                      0.028
 151                      0.486
 152                      0.081
 153                      0.111
 154                      0.001

 [155 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.809           1.285
 1               2                   Denmark  7.646           1.327
 2               3               Switzerland  7.560           1.391
 3               4                   Iceland  7.504           1.327
 4               5                    Norway  7.488           1.424
 ..            ...                       ...    ...             ...
 148           149  Central African Republic  3.476           0.041
 149           150                    Rwanda  3.312           0.343
 150           151                  Zimbabwe  3.299           0.426
 151           152               South Sudan  2.817           0.289
 152           153               Afghanistan  2.567           0.301

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.500                    0.961                         0.662
 1             1.503                    0.979                         0.665
 2             1.472                    1.041                         0.629
 3             1.548                    1.001                         0.662
 4             1.495                    1.008                         0.670
 ..              ...                      ...                           ...
 148           0.000                    0.000                         0.293
 149           0.523                    0.572                         0.604
 150           1.048                    0.375                         0.377
 151           0.553                    0.209                         0.066
 152           0.356                    0.266                         0.000

      Generosity  Perceptions of corruption
 0         0.160                      0.478
 1         0.243                      0.495
 2         0.269                      0.408
 3         0.362                      0.145
 4         0.288                      0.434
 ..          ...                        ...
 148       0.254                      0.028
 149       0.236                      0.486
 150       0.151                      0.081
 151       0.210                      0.111
 152       0.135                      0.001

 [153 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.769           1.340           1.587
 3                     Denmark      7.600           1.383           1.573
 4                      Norway      7.554           1.488           1.582
 ..                        ...        ...             ...             ...
 153                    Rwanda      3.334           0.359           0.711
 154                  Tanzania      3.231           0.476           0.885
 155               Afghanistan      3.203           0.350           0.517
 156  Central African Republic      3.083           0.026           0.000
 157               South Sudan      2.853           0.306           0.575

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.986                         0.596       0.153
 3                      0.996                         0.592       0.252
 4                      1.028                         0.603       0.271
 ..                       ...                           ...         ...
 153                    0.614                         0.555       0.217
 154                    0.499                         0.417       0.276
 155                    0.361                         0.000       0.158
 156                    0.105                         0.225       0.235
 157                    0.295                         0.010       0.202

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.410
 4                        0.341
 ..                         ...
 153                      0.411
 154                      0.147
 155                      0.025
 156                      0.035
 157                      0.091

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[48] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                    1               3
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                      Norway      7.537            0.039           1.616
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2             1.534                    0.797                         0.635
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2         0.362       0.316       2.277
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0              1              3                    Norway  7.537
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...

In [44]:
df2018_raw = tables[13]
df2018_raw.head(200)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...
151,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

### Dataset 4: 2017
 - Webscrape from Wikipedia
 - Store webscraped data into DataFrame

In [33]:
# 2017 table:
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report#2017_report'

In [34]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2020 World Happiness Report, released on M...,
                                         Descriptions
 0  The 2019 World Happiness Report focuses commun...,
                                         Descriptions
 0  The 2018 iteration was released on 20 March an...,
                                         Descriptions
 0  The fifth World Happiness Report emphasizes th...,
                                         Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 150                                                149
 151                                                150
 152                                                151
 153                                                152
 154                                                153

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.809           1.285           1.500
 3                     Denmark      7.646           1.327           1.503
 4                 Switzerland      7.560           1.391           1.472
 ..                        ...        ...             ...             ...
 150  Central African Republic      3.476           0.041           0.000
 151                    Rwanda      3.312           0.343           0.523
 152                  Zimbabwe      3.299           0.426           1.048
 153               South Sudan      2.817           0.289           0.553
 154               Afghanistan      2.567           0.301           0.356

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.961                         0.662       0.160
 3                      0.979                         0.665       0.243
 4                      1.041                         0.629       0.269
 ..                       ...                           ...         ...
 150                    0.000                         0.293       0.254
 151                    0.572                         0.604       0.236
 152                    0.375                         0.377       0.151
 153                    0.209                         0.066       0.210
 154                    0.266                         0.000       0.135

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.478
 3                        0.495
 4                        0.408
 ..                         ...
 150                      0.028
 151                      0.486
 152                      0.081
 153                      0.111
 154                      0.001

 [155 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.809           1.285
 1               2                   Denmark  7.646           1.327
 2               3               Switzerland  7.560           1.391
 3               4                   Iceland  7.504           1.327
 4               5                    Norway  7.488           1.424
 ..            ...                       ...    ...             ...
 148           149  Central African Republic  3.476           0.041
 149           150                    Rwanda  3.312           0.343
 150           151                  Zimbabwe  3.299           0.426
 151           152               South Sudan  2.817           0.289
 152           153               Afghanistan  2.567           0.301

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.500                    0.961                         0.662
 1             1.503                    0.979                         0.665
 2             1.472                    1.041                         0.629
 3             1.548                    1.001                         0.662
 4             1.495                    1.008                         0.670
 ..              ...                      ...                           ...
 148           0.000                    0.000                         0.293
 149           0.523                    0.572                         0.604
 150           1.048                    0.375                         0.377
 151           0.553                    0.209                         0.066
 152           0.356                    0.266                         0.000

      Generosity  Perceptions of corruption
 0         0.160                      0.478
 1         0.243                      0.495
 2         0.269                      0.408
 3         0.362                      0.145
 4         0.288                      0.434
 ..          ...                        ...
 148       0.254                      0.028
 149       0.236                      0.486
 150       0.151                      0.081
 151       0.210                      0.111
 152       0.135                      0.001

 [153 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.769           1.340           1.587
 3                     Denmark      7.600           1.383           1.573
 4                      Norway      7.554           1.488           1.582
 ..                        ...        ...             ...             ...
 153                    Rwanda      3.334           0.359           0.711
 154                  Tanzania      3.231           0.476           0.885
 155               Afghanistan      3.203           0.350           0.517
 156  Central African Republic      3.083           0.026           0.000
 157               South Sudan      2.853           0.306           0.575

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.986                         0.596       0.153
 3                      0.996                         0.592       0.252
 4                      1.028                         0.603       0.271
 ..                       ...                           ...         ...
 153                    0.614                         0.555       0.217
 154                    0.499                         0.417       0.276
 155                    0.361                         0.000       0.158
 156                    0.105                         0.225       0.235
 157                    0.295                         0.010       0.202

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.410
 4                        0.341
 ..                         ...
 153                      0.411
 154                      0.147
 155                      0.025
 156                      0.035
 157                      0.091

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[48] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                    1               3
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                      Norway      7.537            0.039           1.616
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2             1.534                    0.797                         0.635
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2         0.362       0.316       2.277
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0              1              3                    Norway  7.537
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...

In [45]:
df2017_raw = tables[15]
df2017_raw.head(200)

,Overall Rank,Change in rank,Country,Score,Change in score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Trust,Residual
0,1,3,Norway,7.537,0.039,1.616,1.534,0.797,0.635,0.362,0.316,2.277
1,2,1,Denmark,7.522,0.004,1.482,1.551,0.793,0.626,0.355,0.401,2.314
2,3,NaN,Iceland,7.504,0.003,1.481,1.611,0.834,0.627,0.476,0.154,2.323
3,4,2,Switzerland,7.494,0.015,1.565,1.517,0.858,0.620,0.291,0.367,2.277
4,5,NaN,Finland,7.469,0.056,1.444,1.540,0.809,0.618,0.245,0.383,2.430
...,...,...,...,...,...,...,...,...,...,...,...,...
152,151,1,Rwanda,3.471,0.044,0.369,0.946,0.326,0.582,0.253,0.455,0.540
153,152,4,Syria,3.462,0.393,0.777,0.396,0.501,0.082,0.494,0.151,1.062
154,153,4,Tanzania,3.349,0.317,0.511,1.042,0.365,0.390,0.354,0.066,0.621
155,154,3,Burundi,2.905,NaN,0.092,0.630,0.152,0.060,0.204,0.084,1.683
156,155,NaN,Central African Republic,2.693,NaN,0.000,0.000,0.019,0.271,0.281,0.057,2.066

### Dataset 5: 2016
 - Webscrape from Wikipedia
 - Store webscraped data into DataFrame

In [37]:
# 2016 table:
url = 'https://en.wikipedia.org/wiki/World_Happiness_Report#2016_report'

In [38]:
tables = pd.read_html(url)
tables

[                                        Descriptions
 0  The 2020 World Happiness Report, released on M...,
                                         Descriptions
 0  The 2019 World Happiness Report focuses commun...,
                                         Descriptions
 0  The 2018 iteration was released on 20 March an...,
                                         Descriptions
 0  The fifth World Happiness Report emphasizes th...,
                                         Descriptions
 0  The 2016 World Happiness Report -Rome Addition...,
                                         Descriptions
 0  The 2015 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2013 World Happiness Report has eight chap...,
                                         Descriptions
 0  The 2012 World Happiness Report was issued at ...,
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 150                                                149
 151                                                150
 152                                                151
 153                                                152
 154                                                153

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.809           1.285           1.500
 3                     Denmark      7.646           1.327           1.503
 4                 Switzerland      7.560           1.391           1.472
 ..                        ...        ...             ...             ...
 150  Central African Republic      3.476           0.041           0.000
 151                    Rwanda      3.312           0.343           0.523
 152                  Zimbabwe      3.299           0.426           1.048
 153               South Sudan      2.817           0.289           0.553
 154               Afghanistan      2.567           0.301           0.356

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.961                         0.662       0.160
 3                      0.979                         0.665       0.243
 4                      1.041                         0.629       0.269
 ..                       ...                           ...         ...
 150                    0.000                         0.293       0.254
 151                    0.572                         0.604       0.236
 152                    0.375                         0.377       0.151
 153                    0.209                         0.066       0.210
 154                    0.266                         0.000       0.135

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.478
 3                        0.495
 4                        0.408
 ..                         ...
 150                      0.028
 151                      0.486
 152                      0.081
 153                      0.111
 154                      0.001

 [155 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.809           1.285
 1               2                   Denmark  7.646           1.327
 2               3               Switzerland  7.560           1.391
 3               4                   Iceland  7.504           1.327
 4               5                    Norway  7.488           1.424
 ..            ...                       ...    ...             ...
 148           149  Central African Republic  3.476           0.041
 149           150                    Rwanda  3.312           0.343
 150           151                  Zimbabwe  3.299           0.426
 151           152               South Sudan  2.817           0.289
 152           153               Afghanistan  2.567           0.301

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.500                    0.961                         0.662
 1             1.503                    0.979                         0.665
 2             1.472                    1.041                         0.629
 3             1.548                    1.001                         0.662
 4             1.495                    1.008                         0.670
 ..              ...                      ...                           ...
 148           0.000                    0.000                         0.293
 149           0.523                    0.572                         0.604
 150           1.048                    0.375                         0.377
 151           0.553                    0.209                         0.066
 152           0.356                    0.266                         0.000

      Generosity  Perceptions of corruption
 0         0.160                      0.478
 1         0.243                      0.495
 2         0.269                      0.408
 3         0.362                      0.145
 4         0.288                      0.434
 ..          ...                        ...
 148       0.254                      0.028
 149       0.236                      0.486
 150       0.151                      0.081
 151       0.210                      0.111
 152       0.135                      0.001

 [153 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.769           1.340           1.587
 3                     Denmark      7.600           1.383           1.573
 4                      Norway      7.554           1.488           1.582
 ..                        ...        ...             ...             ...
 153                    Rwanda      3.334           0.359           0.711
 154                  Tanzania      3.231           0.476           0.885
 155               Afghanistan      3.203           0.350           0.517
 156  Central African Republic      3.083           0.026           0.000
 157               South Sudan      2.853           0.306           0.575

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.986                         0.596       0.153
 3                      0.996                         0.592       0.252
 4                      1.028                         0.603       0.271
 ..                       ...                           ...         ...
 153                    0.614                         0.555       0.217
 154                    0.499                         0.417       0.276
 155                    0.361                         0.000       0.158
 156                    0.105                         0.225       0.235
 157                    0.295                         0.010       0.202

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.410
 4                        0.341
 ..                         ...
 153                      0.411
 154                      0.147
 155                      0.025
 156                      0.035
 157                      0.091

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.769           1.340
 1               2                   Denmark  7.600           1.383
 2               3                    Norway  7.554           1.488
 3               4                   Iceland  7.494           1.380
 4               5               Netherlands  7.488           1.396
 ..            ...                       ...    ...             ...
 151           152                    Rwanda  3.334           0.359
 152           153                  Tanzania  3.231           0.476
 153           154               Afghanistan  3.203           0.350
 154           155  Central African Republic  3.083           0.026
 155           156               South Sudan  2.853           0.306

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.587                    0.986                         0.596
 1             1.573                    0.996                         0.592
 2             1.582                    1.028                         0.603
 3             1.624                    1.026                         0.591
 4             1.522                    0.999                         0.557
 ..              ...                      ...                           ...
 151           0.711                    0.614                         0.555
 152           0.885                    0.499                         0.417
 153           0.517                    0.361                         0.000
 154           0.000                    0.105                         0.225
 155           0.575                    0.295                         0.010

      Generosity  Perceptions of corruption
 0         0.153                      0.393
 1         0.252                      0.410
 2         0.271                      0.341
 3         0.354                      0.118
 4         0.322                      0.298
 ..          ...                        ...
 151       0.217                      0.411
 152       0.276                      0.147
 153       0.158                      0.025
 154       0.235                      0.035
 155       0.202                      0.091

 [156 rows x 9 columns],
                                                  Table  \
 0    Overall rank Country or region Score GDP per c...
 1                                         Overall rank
 2                                                    1
 3                                                    2
 4                                                    3
 ..                                                 ...
 153                                                152
 154                                                153
 155                                                154
 156                                                155
 157                                                156

                    Unnamed: 1 Unnamed: 2      Unnamed: 3      Unnamed: 4  \
 0                         NaN        NaN             NaN             NaN
 1           Country or region      Score  GDP per capita  Social support
 2                     Finland      7.632           1.305           1.592
 3                      Norway      7.594           1.456           1.582
 4                     Denmark      7.555           1.351           1.590
 ..                        ...        ...             ...             ...
 153                     Yemen      3.355           0.442           1.073
 154                  Tanzania      3.303           0.455           0.991
 155               South Sudan      3.254           0.337           0.608
 156  Central African Republic      3.083           0.024           0.000
 157                   Burundi      2.905           0.091           0.627

                   Unnamed: 5                    Unnamed: 6  Unnamed: 7  \
 0                        NaN                           NaN         NaN
 1    Healthy life expectancy  Freedom to make life choices  Generosity
 2                      0.874                         0.681       0.202
 3                      0.861                         0.686       0.286
 4                      0.868                         0.683       0.284
 ..                       ...                           ...         ...
 153                    0.343                         0.244       0.083
 154                    0.381                         0.481       0.270
 155                    0.177                         0.112       0.224
 156                    0.010                         0.305       0.218
 157                    0.145                         0.065       0.149

                     Unnamed: 8
 0                          NaN
 1    Perceptions of corruption
 2                        0.393
 3                        0.340
 4                        0.408
 ..                         ...
 153                      0.064
 154                      0.097
 155                      0.106
 156                      0.038
 157                      0.076

 [158 rows x 9 columns],
      Overall rank         Country or region  Score  GDP per capita  \
 0               1                   Finland  7.632           1.305
 1               2                    Norway  7.594           1.456
 2               3                   Denmark  7.555           1.351
 3               4                   Iceland  7.495           1.343
 4               5               Switzerland  7.487           1.420
 ..            ...                       ...    ...             ...
 151           152                     Yemen  3.355           0.442
 152           153                  Tanzania  3.303           0.455
 153           154               South Sudan  3.254           0.337
 154           155  Central African Republic  3.083           0.024
 155           156                   Burundi  2.905           0.091

      Social support  Healthy life expectancy  Freedom to make life choices  \
 0             1.592                    0.874                         0.681
 1             1.582                    0.861                         0.686
 2             1.590                    0.868                         0.683
 3             1.644                    0.914                         0.677
 4             1.549                    0.927                         0.660
 ..              ...                      ...                           ...
 151           1.073                    0.343                         0.244
 152           0.991                    0.381                         0.481
 153           0.608                    0.177                         0.112
 154           0.000                    0.010                         0.305
 155           0.627                    0.145                         0.065

      Generosity  Perceptions of corruption
 0         0.202                      0.393
 1         0.286                      0.340
 2         0.284                      0.408
 3         0.353                      0.138
 4         0.256                      0.357
 ..          ...                        ...
 151       0.083                      0.064
 152       0.270                      0.097
 153       0.224                      0.106
 154       0.218                      0.038
 155       0.149                      0.076

 [156 rows x 9 columns],
                                                  Table      Unnamed: 1  \
 0    Table of data for 2017:[48] Overall Rank Chang...             NaN
 1                                         Overall Rank  Change in rank
 2                                                    1               3
 3                                                    2               1
 4                                                    3             NaN
 ..                                                 ...             ...
 154                                                151               1
 155                                                152               4
 156                                                153               4
 157                                                154               3
 158                                                155             NaN

                    Unnamed: 2 Unnamed: 3       Unnamed: 4      Unnamed: 5  \
 0                         NaN        NaN              NaN             NaN
 1                     Country      Score  Change in score  GDP per capita
 2                      Norway      7.537            0.039           1.616
 3                     Denmark      7.522            0.004           1.482
 4                     Iceland      7.504            0.003           1.481
 ..                        ...        ...              ...             ...
 154                    Rwanda      3.471            0.044           0.369
 155                     Syria      3.462            0.393           0.777
 156                  Tanzania      3.349            0.317           0.511
 157                   Burundi      2.905              NaN           0.092
 158  Central African Republic      2.693              NaN           0.000

          Unnamed: 6               Unnamed: 7                    Unnamed: 8  \
 0               NaN                      NaN                           NaN
 1    Social support  Healthy life expectancy  Freedom to make life choices
 2             1.534                    0.797                         0.635
 3             1.551                    0.793                         0.626
 4             1.611                    0.834                         0.627
 ..              ...                      ...                           ...
 154           0.946                    0.326                         0.582
 155           0.396                    0.501                         0.082
 156           1.042                    0.365                         0.390
 157           0.630                    0.152                         0.060
 158           0.000                    0.019                         0.271

      Unnamed: 9 Unnamed: 10 Unnamed: 11
 0           NaN         NaN         NaN
 1    Generosity       Trust    Residual
 2         0.362       0.316       2.277
 3         0.355       0.401       2.314
 4         0.476       0.154       2.323
 ..          ...         ...         ...
 154       0.253       0.455       0.540
 155       0.494       0.151       1.062
 156       0.354       0.066       0.621
 157       0.204       0.084       1.683
 158       0.281       0.057       2.066

 [159 rows x 12 columns],
     Overall Rank Change in rank                   Country  Score  \
 0              1              3                    Norway  7.537
 1              2              1                   Denmark  7.522
 2              3            NaN                   Iceland  7.504
 3              4              2               Switzerland  7.494
 4              5            NaN                   Finland  7.469
 ..           ...            ...                       ...    ...

In [46]:
df2016_raw = tables[18]
df2016_raw.head(200)

,Overall Rank[51][52],Country,Score,Change OverPrior Year,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Trust
0,1,Denmark,7.526,-0.401,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Switzerland,7.509,0.035,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Iceland,7.501,0.000,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Norway,7.498,0.082,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Finland,7.413,-0.259,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
152,153,Benin,3.484,0.154,NaN,NaN,NaN,NaN,NaN,NaN
153,154,Afghanistan,3.360,0.000,NaN,NaN,NaN,NaN,NaN,NaN
154,155,Togo,3.303,0.100,NaN,NaN,NaN,NaN,NaN,NaN
155,156,Syria,3.069,0.000,NaN,NaN,NaN,NaN,NaN,NaN
156,157,Burundi,2.905,0.000,NaN,NaN,NaN,NaN,NaN,NaN

# TRANSFORM
Clean DataFrames

### Dataset 1-5
 - Create filtered database from specific columns
 - Rename column headers
 - Reset and rename index
 - Confirm values are numeric
 - Check for missing values
 - Sort by country name
 - Reorder columns

In [47]:
df2020_raw.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.809,1.285,1.500,0.961,0.662,0.160,0.478
1,2,Denmark,7.646,1.327,1.503,0.979,0.665,0.243,0.495
2,3,Switzerland,7.560,1.391,1.472,1.041,0.629,0.269,0.408
3,4,Iceland,7.504,1.327,1.548,1.001,0.662,0.362,0.145
4,5,Norway,7.488,1.424,1.495,1.008,0.670,0.288,0.434

In [50]:
df2020_raw.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [51]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

,Overall Rank,Country or Region,Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
0,1,Finland,7.809,1.285,1.500,0.961,0.662,0.160,0.478
1,2,Denmark,7.646,1.327,1.503,0.979,0.665,0.243,0.495
2,3,Switzerland,7.560,1.391,1.472,1.041,0.629,0.269,0.408
3,4,Iceland,7.504,1.327,1.548,1.001,0.662,0.362,0.145
4,5,Norway,7.488,1.424,1.495,1.008,0.670,0.288,0.434

In [54]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

,Country or Region,Score,Overall Rank,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
0,Finland,7.809,1,1.285,1.500,0.961,0.662,0.160,0.478
1,Denmark,7.646,2,1.327,1.503,0.979,0.665,0.243,0.495
2,Switzerland,7.560,3,1.391,1.472,1.041,0.629,0.269,0.408
3,Iceland,7.504,4,1.327,1.548,1.001,0.662,0.362,0.145
4,Norway,7.488,5,1.424,1.495,1.008,0.670,0.288,0.434

In [55]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

,Country or Region,Score,Overall Rank,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
152,Afghanistan,2.567,153,0.301,0.356,0.266,0.000,0.135,0.001
104,Albania,4.883,105,0.907,0.830,0.846,0.462,0.171,0.025
99,Algeria,5.005,100,0.944,1.143,0.745,0.084,0.119,0.129
54,Argentina,5.975,55,1.028,1.373,0.850,0.521,0.070,0.060
115,Armenia,4.677,116,0.808,1.035,0.776,0.378,0.107,0.105

In [56]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

,Country or Region,Score,Overall Rank,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
0,Afghanistan,2.567,153,0.301,0.356,0.266,0.000,0.135,0.001
1,Albania,4.883,105,0.907,0.830,0.846,0.462,0.171,0.025
2,Algeria,5.005,100,0.944,1.143,0.745,0.084,0.119,0.129
3,Argentina,5.975,55,1.028,1.373,0.850,0.521,0.070,0.060
4,Armenia,4.677,116,0.808,1.035,0.776,0.378,0.107,0.105

In [57]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

,Country or Region,Score,Overall Rank,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
id,,,,,,,,,
1,Afghanistan,2.567,153,0.301,0.356,0.266,0.000,0.135,0.001
2,Albania,4.883,105,0.907,0.830,0.846,0.462,0.171,0.025
3,Algeria,5.005,100,0.944,1.143,0.745,0.084,0.119,0.129
4,Argentina,5.975,55,1.028,1.373,0.850,0.521,0.070,0.060
5,Armenia,4.677,116,0.808,1.035,0.776,0.378,0.107,0.105

In [58]:
df2020.dtypes

Country or Region                object
Score                           float64
Overall Rank                      int64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to Make Life Choices    float64
Generosity                      float64
Perceptions of Corruption       float64
dtype: object

In [59]:
df2020.isna().sum()

Country or Region               0
Score                           0
Overall Rank                    0
GDP per Capita                  0
Social Support                  0
Healthy Life Expectancy         0
Freedom to Make Life Choices    0
Generosity                      0
Perceptions of Corruption       0
dtype: int64

In [ ]:
df2020_raw.head()

In [ ]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

In [ ]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

In [ ]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

In [ ]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

In [ ]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

In [ ]:
df2020.dtypes

In [ ]:
df2020.isna().sum()

In [ ]:
df2020_raw.head()

In [ ]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

In [ ]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

In [ ]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

In [ ]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

In [ ]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

In [ ]:
df2020.dtypes

In [ ]:
df2020.isna().sum()

In [ ]:
df2020_raw.head()

In [ ]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

In [ ]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

In [ ]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

In [ ]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

In [ ]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

In [ ]:
df2020.dtypes

In [ ]:
df2020.isna().sum()

In [ ]:
df2020_raw.head()

In [ ]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

In [ ]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

In [ ]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

In [ ]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

In [ ]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

In [ ]:
df2020.dtypes

In [ ]:
df2020.isna().sum()

In [ ]:
df2020_raw.head()

In [ ]:
df2020 = df2020_raw.rename(columns = {"Overall rank": "Overall Rank", "Country or region": "Country or Region",\
                                      "GDP per capita": "GDP per Capita", "Social support": "Social Support",\
                                      "Healthy life expectancy": "Healthy Life Expectancy", "Freedom to make life choices": "Freedom to Make Life Choices",\
                                      "Perceptions of corruption": "Perceptions of Corruption"})
df2020.head()

In [ ]:
df2020 = df2020[["Country or Region", "Score", "Overall Rank", "GDP per Capita", "Social Support",\
                "Healthy Life Expectancy", "Freedom to Make Life Choices", "Generosity", "Perceptions of Corruption"]].copy()
df2020.head()

In [ ]:
df2020 = df2020.sort_values(by = 'Country or Region')
df2020.head()

In [ ]:
df2020 = df2020.reset_index(drop=True)
df2020.head()

In [ ]:
df2020.index += 1; df2020.index.name='id'
df2020.head()

In [ ]:
df2020.dtypes

In [ ]:
df2020.isna().sum()